export interface ClubColors {
    primary: string;
    secondary: string;
  }
  
export function getClubColors(clubName: string): ClubColors {
    const clubColors: { [key: string]: ClubColors } = {
        // Brasileirão
        'América-MG': { primary: '#006030', secondary: '#FFD700' },
        'Atlético-GO': { primary: '#2E8B57', secondary: '#FFFFFF' },
        'Athletico Paranaense': { primary: '#ED1C24', secondary: '#000000' },
        'Atlético-MG': { primary: '#000000', secondary: '#FFD700' },
        'Avaí': { primary: '#003399', secondary: '#FFFFFF' },
        'Bahia': { primary: '#003399', secondary: '#FFFFFF' },
        'Botafogo': { primary: '#000000', secondary: '#FFFFFF' },
        'RB Bragantino': { primary: '#D2003C', secondary: '#001D46' },
        'Ceará': { primary: '#008000', secondary: '#FDE910' },
        'Corinthians': { primary: '#000000', secondary: '#FF0000' },
        'Coritiba': { primary: '#009900', secondary: '#FFFFFF' },
        'Cruzeiro': { primary: '#2F529E', secondary: '#FFFFFF' },
        'Cuiabá': { primary: '#008000', secondary: '#FFFFFF' },
        'Flamengo': { primary: '#FF3F00', secondary: '#000000' },
        'Fluminense': { primary: '#801D1E', secondary: '#FFFFFF' },
        'Fortaleza': { primary: '#FF0000', secondary: '#FFD700' },
        'Grêmio': { primary: '#0D80BF', secondary: '#FFFFFF' },
        'Goiás': { primary: '#006400', secondary: '#FFFFFF' },
        'Internacional': { primary: '#FF0000', secondary: '#FFFFFF' },
        'Juventude': { primary: '#6A5ACD', secondary: '#000000' },
        'Palmeiras': { primary: '#006400', secondary: '#FFFFFF' },
        'Santos': { primary: '#FFFFFF', secondary: '#000000' },
        'São Paulo': { primary: '#000000', secondary: '#FF0000' },
        'Vasco da Gama': { primary: '#000000', secondary: '#FFFFFF' },

        // Premier League
        'Arsenal': { primary: '#EF0107', secondary: '#FFFFFF' },
        'Aston Villa': { primary: '#95BFE5', secondary: '#500000' },
        'Bournemouth': { primary: '#DA291C', secondary: '#000000' },
        'Brentford': { primary: '#B70808', secondary: '#000000' },
        'Brighton': { primary: '#0057B8', secondary: '#FFCD00' },
        'Chelsea': { primary: '#034694', secondary: '#DBA111' },
        'Crystal Palace': { primary: '#1B458F', secondary: '#C4122E' },
        'Everton': { primary: '#003399', secondary: '#FFFFFF' },
        'Fulham': { primary: '#000000', secondary: '#FFFFFF' },
        'Leeds United': { primary: '#1E1E1E', secondary: '#FFCD00' },
        'Leicester City': { primary: '#003090', secondary: '#FDBE11' },
        'Liverpool': { primary: '#C8102E', secondary: '#00B2A9' },
        'Manchester City': { primary: '#6CABDD', secondary: '#1C2C5' },
        'Manchester United': { primary: '#DA291C', secondary: '#FFE500' },
        'Newcastle United': { primary: '#241F20', secondary: '#FFFFFF' },
        'Nottingham Forest': { primary: '#FF0000', secondary: '#FFFFFF' },
        'Southampton': { primary: '#D71920', secondary: '#FFFFFF' },
        'Tottenham': { primary: '#132257', secondary: '#FFFFFF' },
        'West Ham': { primary: '#7A263A', secondary: '#1BB1E7' },
        'Wolves': { primary: '#FDB913', secondary: '#231F20' },

        // La Liga
        'Almería': { primary: '#E30613', secondary: '#0055A4' },
        'Athletic Club': { primary: '#FF3C00', secondary: '#000000' },
        'Atlético Madrid': { primary: '#FFCB05', secondary: '#003C82' },
        'Barcelona': { primary: '#A50044', secondary: '#0066B2' },
        'Real Betis': { primary: '#007A33', secondary: '#EEEEEE' },
        'Celta Vigo': { primary: '#1B458F', secondary: '#FFFFFF' },
        'Cádiz': { primary: '#FEDA04', secondary: '#002868' },
        'Elche': { primary: '#007436', secondary: '#000000' },
        'Espanyol': { primary: '#005DA4', secondary: '#FFFFFF' },
        'Getafe': { primary: '#046A38', secondary: '#FFFFFF' },
        'Girona': { primary: '#EE0000', secondary: '#FFFFFF' },
        'Mallorca': { primary: '#FAA41A', secondary: '#000000' },
        'Osasuna': { primary: '#FF7F00', secondary: '#000000' },
        'Rayo Vallecano': { primary: '#B70500', secondary: '#FFFFFF' },
        'Real Madrid': { primary: '#FFFFFF', secondary: '#000000' },
        'Real Sociedad': { primary: '#0057B8', secondary: '#FFFFFF' },
        'Sevilla': { primary: '#EE0000', secondary: '#FFFFFF' },
        'Valencia': { primary: '#FF7F00', secondary: '#000000' },
        'Real Valladolid': { primary: '#4E157D', secondary: '#FFFFFF' },
        'Villarreal': { primary: '#FFCD00', secondary: '#00529F' },

        // Ligue 1
        'Ajaccio': { primary: '#FF0000', secondary: '#FFFFFF' },
        'Angers': { primary: '#000000', secondary: '#FFFFFF' },
        'Auxerre': { primary: '#FFEB00', secondary: '#000000' },
        'Brest': { primary: '#FF0000', secondary: '#FFFFFF' },
        'Clermont Foot': { primary: '#ED1C24', secondary: '#000000' },
        'Lens': { primary: '#EE0000', secondary: '#FFFFFF' },
        'Lille': { primary: '#FFED00', secondary: '#000000' },
        'Lorient': { primary: '#E30613', secondary: '#000000' },
        'Lyon': { primary: '#0C68C8', secondary: '#FFFFFF' },
        'Marseille': { primary: '#0052A4', secondary: '#FFFFFF' },
        'Monaco': { primary: '#D9012C', secondary: '#FFFFFF' },
        'Montpellier': { primary: '#00529F', secondary: '#FFB200' },
        'Nantes': { primary: '#FFCC00', secondary: '#0066B2' },
        'Nice': { primary: '#EF1C24', secondary: '#0055A4' },
        'Paris SG': { primary: '#0044FF', secondary: '#FFFFFF' },
        'Reims': { primary: '#FFD700', secondary: '#FF0000' },
        'Rennes': { primary: '#EF1C24', secondary: '#000000' },
        'Strasbourg': { primary: '#6ABDE6', secondary: '#FFFFFF' },
        'Toulouse': { primary: '#005CBF', secondary: '#FFD700' },
        'Troyes': { primary: '#005CBF', secondary: '#EF2F24' },

        // Bundesliga
        'Augsburg': { primary: '#FFFFFF', secondary: '#F20000' },
        'Bayern Munich': { primary: '#DC052D', secondary: '#FFFFFF' },
        'Bochum': { primary: '#1B458F', secondary: '#FFFFFF' },
        'Borussia Dortmund': { primary: '#FFD700', secondary: '#000000' },
        'Eintracht Frankfurt': { primary: '#000000', secondary: '#FFD700' },
        'Freiburg': { primary: '#8E191B', secondary: '#000000' },
        'Hertha BSC': { primary: '#0072CE', secondary: '#FFFFFF' },
        'Hoffenheim': { primary: '#004982', secondary: '#FFFFFF' },
        'Köln': { primary: '#F90000', secondary: '#FFFFFF' },
        'Leverkusen': { primary: '#E00000', secondary: '#000000' },
        'Borussia M\'Gladbach': { primary: '#000000', secondary: '#92BCEA' },
        'Mainz 05': { primary: '#FFCC00', secondary: '#000000' },
        'RB Leipzig': { primary: '#FFDF00', secondary: '#000000' },
        'Schalke 04': { primary: '#004980', secondary: '#FFFFFF' },
        'Stuttgart': { primary: '#FFD700', secondary: '#000000' },
        'Union Berlin': { primary: '#B60000', secondary: '#000000' },
        'Werder Bremen': { primary: '#008000', secondary: '#FFFFFF' },
        'Wolfsburg': { primary: '#009E3C', secondary: '#FFFFFF' },

        // Serie A
        'Atalanta': { primary: '#1e71b8', secondary: '#000000' },
        'Bologna': { primary: '#BF0A30', secondary: '#0A56A3' },
        'Cremonese': { primary: '#F20000', secondary: '#FFFFFF' },
        'Empoli': { primary: '#005397', secondary: '#FFFFFF' },
        'Fiorentina': { primary: '#551E37', secondary: '#FFFFFF' },
        'Hellas Verona': { primary: '#FFD700', secondary: '#A1A1A4' },
        'Inter': { primary: '#0044FF', secondary: '#FFFFFF' },
        'Juventus': { primary: '#000000', secondary: '#FFFFFF' },
        'Lazio': { primary: '#77BBFF', secondary: '#000080' },
        'Lecce': { primary: '#E60000', secondary: '#000000' },
        'Milan': { primary: '#E60000', secondary: '#000000' },
        'Monza': { primary: '#FF0000', secondary: '#000000' },
        'Napoli': { primary: '#0044FF', secondary: '#FFFFFF' },
        'Roma': { primary: '#7F2623', secondary: '#F9BC2D' },
        'Salernitana': { primary: '#0052B4', secondary: '#FFFFFF' },
        'Sampdoria': { primary: '#004693', secondary: '#FFFFFF' },
        'Sassuolo': { primary: '#3FBCDD', secondary: '#FFD700' },
        'Spezia': { primary: '#0C2C56', secondary: '#FFFFFF' },
        'Torino': { primary: '#7F1C22', secondary: '#FFFFFF' },
        'Udinese': { primary: '#000000', secondary: '#FFFFFF' },
    };
    const club = clubColors[clubName];
    if (club == null)
      throw new Error(`Unknown club: ${clubName}`);

    return club;
}